### ISSUE TITLE
More on KenLM

### ISSUE THREAD

**Issue by xumx** [siddBanPsu/AbTextSumm#2]
Could you explain a little bit more on the LM that you have used in the experiment? Is there a way to download the "lm-3g.klm" that you have used in the Example code?

**Comment by siddBanPsu** [comment]
You can use the model 20k 3gram from here: https://www.keithv.com/software/giga/
This is in arpa format, but you can use Kenlm to convert it to binary and use it to make it faster.

**Comment by ghost** [comment]
Hi there,

Could you just go into a bit more detail how to do that in Linux?

 I have Kenlm installed and I have downloaded lm_giga_20k_vp_3gram.arpa
 When i try to run:
 bin/build_binary lm_giga_20k_vp_3gram.arpa lm-3g.klm.binary

 it says "No such file or directory". 

Many thanks for sharing

James

**Comment by siddBanPsu** [comment]
@jdr6  James, I think your lm_giga_20k_vp_3gram.arpa should be in the directory where the bin directory is located. It cannot find the file.

**Comment by PratikNalage** [comment]
how to make .klm file from .binary one?
