### ISSUE TITLE
Missing lm-3g.klm file

### ISSUE THREAD

**Issue by hipoglucido** [siddBanPsu/AbTextSumm#3]
Hello, first of all, thanks for your project.
I am testing some alternatives in order to perform abstractive summaries and I wanted to run your `Example.py` to do so.

As I have seen, it is required in your code (`Line 107` in `Example.py`) the file `resources/lm-3g.klm`:
`lm = kenlm.LanguageModel(RESOURCES_DIR+'/lm-3g.klm')`

It gives a an Exception because the file it is not included in the project.

Where could I find it? 

I have searched on the internet with no luck :(

**Comment by siddBanPsu** [comment]
@hipoglucido  Refer to this issue: #2 . You can find the Language models here: https://www.keithv.com/software/giga/. You need to convert them to kenlm format and preferred is binary that will make lookup faster.
